export const AUTH_TAB = 'AUTH_TAB';
export const WELCOME_SCREEN = 'WELCOME_SCREEN';
export const LOGIN_SCREEN = 'LOGIN_SCREEN';
export const REGISTER_SCREEN = 'REGSITER_SCREEN';
export const FORGET_PASS = 'FORGET_PASS';
export const CONFIRM_OTP_SCREEN = 'CONFIRM_OTP_SCREEN';
export const CREATE_NEW_PASS = 'CREATE_NEW_PASS';
export const OTP_FORGET_PASS_SCREEN = 'OTP_FORGET_PASS_SCREEN';


export const HOME_SCREEN = 'HOME_SCREEN';

export const NOTIFICATION_SCREEN = 'NOTIFICATION_SCREEN';
export const PROFILE_SCREEN = 'PROFILE_SCREEN';

export const PETS_SCREEN = 'PETS_SCREEN';
export const PRODUCTS_SCREEN = 'PRODUCTS_SCREEN';
export const SERVICES_SCREEN = 'SERVICES_SCREEN';

export const INSERT_PETS_SCREEN = 'INSERT_PETS_SCREEN';
export const INSERT_PRODUCTS_SCREEN = 'INSERT_PRODUCTS_SCREEN';
export const INSERT_SERVICES_SCREEN = 'INSERT_SERVICES_SCREEN';

export const PETS_DETAIL_SCREEN = 'PETS_DETAIL_SCREEN';
export const PRODUCTS_DETAIL_SCREEN = 'PRODUCTS_DETAIL_SCREEN';
export const SERVICES_DETAIL_SCREEN = 'SERVICES_DETAIL_SCREEN';


export const EDIT_PROFILE_ACCOUNT = 'EDIT_PROFILE_ACCOUNT';
export const EDIT_PROFILE_ADDRESS = 'EDIT_PROFILE_ADDRESS';

export const CHART_SCREEN = 'CHART_SCREEN';

export const MAIN_TAB = 'MAIN_TAB';

