export const AUTH_TAB = 'AUTH_TAB';
export const WELCOME_SCREEN = 'WELCOME_SCREEN';
export const LOGIN_SCREEN = 'LOGIN_SCREEN';
export const REGISTER_SCREEN = 'REGSITER_SCREEN';
export const FORGET_PASS = 'FORGET_PASS';
export const CONFIRM_OTP_SCREEN = 'CONFIRM_OTP_SCREEN';
export const CREATE_NEW_PASS = 'CREATE_NEW_PASS';


export const HOME_SCREEN = 'HOME_SCREEN';
export const FAVOURITE_PRODUCTS_SCREEN = 'FAVOURITE_PRODUCTS_SCREEN';
export const FAVOURITE_PETS_SCREEN = 'FAVOURITE_PETS_SCREEN';
export const FAVOURITE_SERVICES_SCREEN = 'FAVOURITE_SERVICES_SCREEN';

export const HANDBOOK_SCREEN = 'HANDBOOK_SCREEN';
export const PROFILE_SCREEN = 'PROFILE_SCREEN';

export const PETS_SCREEN = 'PETS_SCREEN';
export const PRODUCTS_SCREEN = 'PRODUCTS_SCREEN';
export const SERVICES_SCREEN = 'SERVICES_SCREEN';

export const PETS_DETAIL_SCREEN = 'PETS_DETAIL_SCREEN';
export const PRODUCTS_DETAIL_SCREEN = 'PRODUCTS_DETAIL_SCREEN';
export const SERVICES_DETAIL_SCREEN = 'SERVICES_DETAIL_SCREEN';

export const PROFILE_SHOP_SCREEN = 'PROFILE_SHOP_SCREEN';

export const FILTER_PETS_SCREEN = 'FILTER_PETS_SCREEN';
export const FILTER_PRODUCTS_SCREEN = 'FILTER_PRODUCTS_SCREEN';
export const FILTER_SERVICES_SCREEN = 'FILTER_SERVICES_SCREEN';
export const FILTER_PROFILE_SHOP_SCREEN = 'FILTER_PROFILE_SHOP_SCREEN';

export const HANDBOOK_DETAIL_SCREEN = 'HANDBOOK_DETAIL_SCREEN';

export const EDIT_PROFILE_ACCOUNT = 'EDIT_PROFILE_ACCOUNT';
export const EDIT_PROFILE_ADDRESS = 'EDIT_PROFILE_ADDRESS';



export const CART_SCREEN = 'CART_SCREEN';
export const HISTORY_PRODUCTS = 'HISTORY_PRODUCTS';
export const HISTORY_SERVICES = 'HISTORY_SERVICES';


export const MAIN_TAB = 'MAIN_TAB';